// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bitirmeSonProje.Models;

namespace bitirmeSonProje.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20230112162310_ver1")]
    partial class ver1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("bitirmeSonProje.Models.DersProgrami", b =>
                {
                    b.Property<string>("Gun")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DersAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DersKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DersSaati")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnKosul")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Gun");

                    b.ToTable("DersProgramis");
                });

            modelBuilder.Entity("bitirmeSonProje.Models.Duyuru", b =>
                {
                    b.Property<int>("DuyuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuyuruAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DuyuruTur")
                        .HasColumnType("int");

                    b.Property<string>("Resmi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DuyuruId");

                    b.HasIndex("DuyuruTur");

                    b.ToTable("Duyurus");
                });

            modelBuilder.Entity("bitirmeSonProje.Models.DuyuruTuru", b =>
                {
                    b.Property<int>("DuyuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("DuyuruId");

                    b.ToTable("DuyuruTurus");
                });

            modelBuilder.Entity("bitirmeSonProje.Models.Kisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("ResimYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeciliKisiId")
                        .HasColumnType("int");

                    b.Property<string>("Soyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcKimlikNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unvan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kisis");
                });

            modelBuilder.Entity("bitirmeSonProje.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OnayliMi")
                        .HasColumnType("bit");

                    b.Property<string>("Parola")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("TamAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Kullanicis");
                });

            modelBuilder.Entity("bitirmeSonProje.Models.OfisSaati", b =>
                {
                    b.Property<bool>("MusatilikDurumu")
                        .HasColumnType("bit");

                    b.Property<string>("OfisSaatiBaslangic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfisSaatiBitis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfisSaatiGun")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusatilikDurumu");

                    b.ToTable("OfisSaatis");
                });

            modelBuilder.Entity("bitirmeSonProje.Models.SiteAyarlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SecilenKisiId")
                        .HasColumnType("int");

                    b.Property<string>("SiteAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteLogo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SiteAyarlars");
                });

            modelBuilder.Entity("bitirmeSonProje.Models.Duyuru", b =>
                {
                    b.HasOne("bitirmeSonProje.Models.DuyuruTuru", "DuyuruTuru")
                        .WithMany()
                        .HasForeignKey("DuyuruTur");

                    b.Navigation("DuyuruTuru");
                });
#pragma warning restore 612, 618
        }
    }
}
